config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "staff-menu", to: "pages#staff_menu", as: :staff_menu
  get "sign-in", to: "sessions#new", as: :sign_in
  post "sign-in", to: "sessions#create"
  delete "sign-out", to: "sessions#destroy"
  get "sign-up", to: "users#new", as: :sign_up

  namespace :staff do
    namespace :review do
      resources :staff_profiles, only: [:update]
    end
    resources :characters, only: [:destroy, :index, :update]
    resources :character_inventories, only: [:update]
    resources :components, except: [:create, :destroy, :update] do
      collection do
        resources :filters, only: [:show]
        resources :pictures, only: [:index]
      end
    end
    resources :events, only: [:create, :destroy, :edit, :new, :update] do
      resources :bookings, only: [:index]
      resources :self_reports, only: [:index]
    end
    resources :ingredients, controller: :components, only: [:create, :destroy, :update]
    resources :inventories, only: [:destroy]
    resources :professions, only: [:index, :show]
    resources :profession_links, only: [:create, :new, :update]
    resources :profiles, only: [:index]
    resources :recipes do
      resources :character_recipes, only: [:new, :create]
    end
    resources :receipts, only: [:show]
    resources :review_profiles, only: [:index]
    resources :staff_profiles, only: [:create, :update]
    resources :users, only: [:index, :show] do
      resources :characters, only: [:edit, :show] do
        resources :character_recipes, only: [:index, :new, :create, :show]
        resources :inventories, only: [:index]
      end
    end
    resources :recipes
    resources :user_staff_statuses, only: [:update]
    resources :user_editor_statuses, only: [:update]
  end

  resources :account_confirmations, only: [:edit]
  resources :bank_accounts
  resources :bookings, only: [:new, :update]
  resources :cash_bookings, only: [:new, :create]
  resources :characters, only: [:create, :edit, :index, :new, :show, :update] do
    resources :character_recipes, only:[:index, :show]
    resources :ingredient_transfers, only:[:new, :create]
    resources :bank_accounts, only: [:show, :edit, :new] do
      resources :bank_transactions
    end
  end
  resources :events, only: [:index, :show]
  resources :password_resets, only: [:create, :edit, :new, :update]
  resources :receipts, only: [:create]
  resources :recipes, only:[:show]
  resources :staff, only: [:index] do
    resources :messages, only: [:create, :new]
  end
  resources :users, only: [:create, :edit, :update]
end

app/models/character.rb
class Character < ApplicationRecord

  before_validation :generate_slug
  before_validation :strip_name

  belongs_to :user

  enum race: {
    other: 0,
    dagon: 1,
    elf: 2,
    haroc: 3,
    human: 4,
    krosan: 5,
    mystic: 6,
    ritika: 7,
    undead_ghoul: 8,
    undead_lyche: 9,
    undead_vampyre: 10,
    wyldling: 11
  }

  has_many :bookings
  has_many :character_professions
  has_many :professions, through: :character_professions
  has_many :character_profession_links
  has_many :profession_links, through: :character_profession_links, source: :link
  has_many :events, through: :bookings
  has_many :inventories
  has_many :ingredients, through: :inventories
  accepts_nested_attributes_for :inventories
  has_one :bank_account
  has_one :recipe_book
  has_many :character_recipes
  has_many :recipes, through: :character_recipes

  validates_numericality_of :drake, allow_nil: true, only_integer: true, greater_than_or_equal_to: 0
  validates_presence_of :name, :slug, :user
  validates_uniqueness_of :name, :slug

  scope :by_name, -> { order(:name) }

  def alchemist?
    professions.include?(Profession.alchemy)
  end

  def artisan?
    professions.include?(Profession.artisan)
  end

  def ritualist?
    professions.include?(Profession.ritualist)
  end

  def scholar?
    professions.any? { |profession| Profession.scholar.include?(profession) }
  end

  def to_param
    slug
  end

  protected

  def generate_slug
    self.slug ||= name.parameterize
  end

  def strip_name
    self.name = self.name.strip
  end
end

app/controllers/admin/characters_controller.rb
class Admin::CharactersController < ApplicationController
  before_action :authenticate_staff!

  def destroy
    @character = Character.find_by(slug: params[:id])
    @time_string = Time.now.to_formatted_s(:number)
    if @character.update(archived: true, name: "[Archived: #{@time_string}] #{@character.name}", slug: "archived-#{@time_string}-#{@character.slug}")
      flash[:success] = "Character deleted successfully."
      redirect_to staff_characters_path
    else
      flash.now[:alert] = "There was a problem deleting your character."
      render :show
    end
  end

  def edit
    @character = Character.find_by(slug: params[:id])
  end

  def index
    @characters = Character.where(archived: false)
  end

  def show
    @character = Character.find_by(slug: params[:id])
    @markdown = new_markdown
  end

  def update
    @character = Character.find_by(slug: params[:id])
    if @character.update(staff_character_params)
      flash[:success] = "Character updated successfully."
      redirect_to staff_user_character_path(@character.user, @character)
    else
      flash.now[:alert] = "There was a problem updating your character."
      render :edit
    end
  end

  protected

  def staff_character_params
    params.require(:character).permit(:name, :slug, :race, :user_id, :history)
  end
end

app/controllers/api/v1/characters_controller.rb
class Api::V1::CharactersController < Api::ApiController
  def show
    character = Character.find_by(slug: params[:id])
    render json: character
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  before_action :authenticate_user!

  def create
    @character = Character.new(character_params)
    @character.user = current_user
    if @character.save
      flash[:success] = "Character created successfully."
      redirect_to characters_path
    else
      flash.now[:alert] = "There was a problem creating your character."
      render :new
    end
  end

  def edit
    @character = Character.find_by(slug: params[:id])
    @user = @character.user
    authorize_record_owner(@user)
  end

  def index
    @characters = current_user.characters.where(archived: false)
  end

  def new
    @character = Character.new
  end

  def show
    @character = Character.find_by(slug: params[:id])
    @user = @character.user
    @markdown = new_markdown
    authorize_record_owner(@user)
  end

  def update
    @character = Character.find_by(slug: params[:id])
    @user = @character.user
    authorize_record_owner(@user)
    if @character.update(update_params)
      flash[:success] = "Character updated successfully."
      redirect_to character_path(@character)
    else
      flash.now[:alert] = "There was a problem updating your character."
      render :edit
    end
  end

  protected

  def character_params
    params.require(:character).permit(:name, :race)
  end

  def update_params
    params.require(:character).permit(:history)
  end

end

app/controllers/staff/characters_controller.rb
class Staff::CharactersController < ApplicationController
  before_action :authenticate_staff!
  before_action :authenticate_staff_editor!, except: [:index, :show]

  def destroy
    @character = Character.find_by(slug: params[:id])
    @time_string = Time.now.to_formatted_s(:number)
    if @character.update(archived: true, name: "[Archived: #{@time_string}] #{@character.name}", slug: "archived-#{@time_string}-#{@character.slug}")
      flash[:success] = "Character deleted successfully."
      redirect_to staff_characters_path
    else
      flash.now[:alert] = "There was a problem deleting your character."
      render :show
    end
  end

  def edit
    @character = Character.find_by(slug: params[:id])
    @professions = Profession.order(:name)
  end

  def index
    @characters = Character.where(archived: false)
  end

  def show
    @character = Character.find_by(slug: params[:id])
    @bank_account = BankAccount.where('character_id =?', @character.id)
    @markdown = new_markdown
  end

  def update
    @character = Character.find_by(slug: params[:id])
    if @character.update(staff_character_params)
      flash[:success] = "Character updated successfully."
      redirect_to staff_user_character_path(@character.user, @character)
    else
      flash.now[:alert] = "There was a problem updating your character."
      @professions = Profession.order(:name)
      render :edit
    end
  end

  protected

  def staff_character_params
    params.require(:character).permit(:name, :slug, :race, :user_id, :drake, :history, profession_ids: [], profession_link_ids: [])
  end
end

app/views/characters/edit.html.haml
-content_for :title do
  MyCrossroads: Edit #{@character.name}
.row
  .small-12.columns
    %nav{"aria-label": "You are here:", role: "navigation"}
      %ul.breadcrumbs
        %li
          =link_to "My Characters", characters_path
        %li
          =link_to @character.name, character_path(@character)
        %li
          %span.show-for-sr Current:
          Edit
    %h1.text-center= @character.name
    =form_for @character do |f|
      .form-errors
        -if @character.errors.present?
          .callout.alert
            %ul
              -@character.errors.messages.each do |attribute, messages|
                %li
                  %strong
                    =attribute.to_s.humanize
                  ="#{messages.to_sentence}."
      .form-inputs
        %fieldset
          =f.label :history, "Character History"
          =f.text_area :history
      .form-actions
        =f.submit "Save", class: "button"
    %p
      Character histories support markdown. For more information on Markdown syntax, click
      =link_to "here.", "https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet", target: "_blank"
    %table
      %thead
        %tr
          %th syntax
          %th rendered as
      %tbody
        %tr
          %td *italics*
          %td
            %em italics
        %tr
          %td **bold**
          %td
            %strong bold
        %tr
          %td [link](http://enthusiastick.com)
          %td
            =link_to "link", "http://enthusiastick.com", rel: "nofollow"
        %tr
          %td
            * item 1
            %br/
            * item 2
            %br/
            * item 3
          %td
            %ul
              %li item 1
              %li item 2
              %li item 3

app/views/characters/index.html.haml
-content_for :title do
  MyCrossroads: My Characters
.row
  .small-12.columns
    %h1.text-center My Characters
    %p.text-center= link_to "Add New Character", new_character_path, class: "button"
    %table.hover.stack.datatables
      %thead
        %tr
          %th Name
          %th Race
      %tbody
        -@characters.each do |character|
          %tr
            %td= link_to character.name, character_path(character)
            %td= character.race.titleize

app/views/characters/new.html.haml
-content_for :title do
  MyCrossroads: New Character
.row
  .small-12.columns
    %h1.text-center New Character
    =form_for @character do |f|
      .form-inputs
        %fieldset
          =render partial: "text_field_with_errors", locals: {attribute: :name, form: f, model: @character}
        %fieldset
          =f.label :race
          =f.select :race, options_for_select(Character.enum_collection(:races))
      .form-actions
        =f.submit "Create", class: "button"

app/views/characters/show.html.haml
-content_for :title do
  MyCrossroads: #{@character.name}
.row
  .small-12.columns
    %nav{"aria-label": "You are here:", role: "navigation"}
      %ul.breadcrumbs
        %li
          =link_to "My Characters", characters_path
        %li
          %span.show-for-sr Current:
          =@character.name
    %h1.text-center
      =@character.name
      %a{"data-open": "historyModal"}
        %i.fa.fa-book{"aria-hidden": "true"}
      -if @character.alchemist?
        =link_to character_character_recipes_path(@character.slug) do
          %i.fa.fa-flask{"aria-hidden": "true"}
      -unless @character.bank_account.nil?
        =link_to character_bank_account_path(@character, @character.bank_account) do
          %i.fa.fa-diamond{"aria-hidden": "true"}
    %h3.text-center= @character.race.titleize
    -unless @character.drake.nil?
      %p.text-center
        =number_with_delimiter(@character.drake)
        Drake
    -unless @character.inventories.empty?
      .callout
        %h2.text-center Components Inventory
        %p.text-center
          =link_to "Send Components to another Character", new_character_ingredient_transfer_path(@character.slug)
        %table.hover.datatables{ data: { page: { length: "25" }, order: "[[1,\"asc\"]]" } }
          %thead
            %tr
              %th.text-right Quantity
              %th Component
              -if @character.artisan? || @character.scholar?
                %th.text-center Crafting
              -else
                %th.text-center
                  %i.fa.fa-question-circle
              -if @character.alchemist? || @character.scholar?
                %th.text-center Processes
              -else
                %th.text-center
                  %i.fa.fa-question-circle
              -if @character.ritualist? || @character.scholar?
                %th.text-center Ritual
              -else
                %th.text-center
                  %i.fa.fa-question-circle
          %tbody
            -@character.inventories.each do |inventory|
              %tr
                %td.text-right= inventory.quantity
                %td
                  =inventory.ingredient.name
                  -if inventory.ingredient.picture.present?
                    %a.float-right{ data: { open: inventory.ingredient.name.parameterize } }
                      %i.fa.fa-eye
                %td.text-center
                  -if inventory.unlocked_crafting?
                    =inventory.ingredient.crafting
                  -else
                    %i.fa.fa-lock
                %td
                  %span
                    -if @character.alchemist? || @character.scholar?
                      Extraction:
                    -else
                      %i.fa.fa-question-circle
                    -if inventory.unlocked_extraction?
                      =inventory.ingredient.process_extraction
                      %br/
                    -else
                      %i.fa.fa-lock
                      &nbsp;
                  %span
                    -if @character.alchemist? || @character.scholar?
                      Calcination:
                    -else
                      %i.fa.fa-question-circle
                    -if inventory.unlocked_calcination?
                      =inventory.ingredient.process_calcination
                      %br/
                    -else
                      %i.fa.fa-lock
                      &nbsp;
                  %span
                    -if @character.alchemist? || @character.scholar?
                      Dissolution:
                    -else
                      %i.fa.fa-question-circle
                    -if inventory.unlocked_dissolution?
                      =inventory.ingredient.process_dissolution
                      %br/
                    -else
                      %i.fa.fa-lock
                      &nbsp;
                  %span
                    -if @character.alchemist? || @character.scholar?
                      Concentration:
                    -else
                      %i.fa.fa-question-circle
                    -if inventory.unlocked_concentration?
                      =inventory.ingredient.process_concentration
                    -else
                      %i.fa.fa-lock
                      &nbsp;
                %td
                  -if @character.ritualist? || @character.scholar?
                    -if inventory.unlocked_ritual?
                      =inventory.ingredient.ritual_properties.to_sentence
                    -else
                      Attribute:
                      %i.fa.fa-question-circle
                      &nbsp;
                      Elemental Affinity:
                      %i.fa.fa-question-circle
                      &nbsp;
                      Gender:
                      %i.fa.fa-question-circle
                  -else
                    -if inventory.unlocked_ritual?
                      =inventory.ingredient.ritual_properties.to_sentence
                    -else
                      -3.times do
                        %i.fa.fa-question-circle
                        %i.fa.fa-lock
                        &nbsp;
    -unless @character.professions.empty?
      -@character.professions.order(:name).each do |profession|
        -unless @character.profession_links.where(profession: profession).empty?
          .callout
            %h2.text-center= profession.name
            .menu-centered
              %ul.menu
                -@character.profession_links.where(profession: profession).order(:name).each do |link|
                  %li
                    =link_to link.url, target: "_blank" do
                      %i.fa.fa-link
                      =link.name
.reveal#historyModal{"data-reveal": ""}
  %h2.margin-bottom-none.text-center
    Character History
    =link_to edit_character_path(@character) do
      %i.fa.fa-pencil-square-o{"aria-hidden": "true"}
  %hr/
  -if @character.history.blank?
    %p
      %em (blank)
  -else
    =raw @markdown.render(@character.history)
  %button.close-button{"data-close": "", "aria-label": "Close modal", "type": "button"}
    %span{"aria-hidden": "true"}
      &times;
-@character.inventories.each do |inventory|
  -if inventory.ingredient.picture.present?
    .reveal{ id: "#{inventory.ingredient.name.parameterize}", data: { reveal: "" } }
      %span.label= inventory.ingredient.name
      =image_tag(inventory.ingredient.picture.url, alt: "Picture of #{inventory.ingredient.name}")
      %button.close-button{ data: { close: "" }, aria: { label:  "Close modal"}, type: "button" }
        %span{ aria: { hidden: "true" } }
          &times;