config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "staff-menu", to: "pages#staff_menu", as: :staff_menu
  get "sign-in", to: "sessions#new", as: :sign_in
  post "sign-in", to: "sessions#create"
  delete "sign-out", to: "sessions#destroy"
  get "sign-up", to: "users#new", as: :sign_up

  namespace :staff do
    namespace :review do
      resources :staff_profiles, only: [:update]
    end
    resources :characters, only: [:destroy, :index, :update]
    resources :character_inventories, only: [:update]
    resources :components, except: [:create, :destroy, :update] do
      collection do
        resources :filters, only: [:show]
        resources :pictures, only: [:index]
      end
    end
    resources :events, only: [:create, :destroy, :edit, :new, :update] do
      resources :bookings, only: [:index]
      resources :self_reports, only: [:index]
    end
    resources :ingredients, controller: :components, only: [:create, :destroy, :update]
    resources :inventories, only: [:destroy]
    resources :professions, only: [:index, :show]
    resources :profession_links, only: [:create, :new, :update]
    resources :profiles, only: [:index]
    resources :recipes do
      resources :character_recipes, only: [:new, :create]
    end
    resources :receipts, only: [:show]
    resources :review_profiles, only: [:index]
    resources :staff_profiles, only: [:create, :update]
    resources :users, only: [:index, :show] do
      resources :characters, only: [:edit, :show] do
        resources :character_recipes, only: [:index, :new, :create, :show]
        resources :inventories, only: [:index]
      end
    end
    resources :recipes
    resources :user_staff_statuses, only: [:update]
    resources :user_editor_statuses, only: [:update]
  end

  resources :account_confirmations, only: [:edit]
  resources :bank_accounts
  resources :bookings, only: [:new, :update]
  resources :cash_bookings, only: [:new, :create]
  resources :characters, only: [:create, :edit, :index, :new, :show, :update] do
    resources :character_recipes, only:[:index, :show]
    resources :ingredient_transfers, only:[:new, :create]
    resources :bank_accounts, only: [:show, :edit, :new] do
      resources :bank_transactions
    end
  end
  resources :events, only: [:index, :show]
  resources :password_resets, only: [:create, :edit, :new, :update]
  resources :receipts, only: [:create]
  resources :recipes, only:[:show]
  resources :staff, only: [:index] do
    resources :messages, only: [:create, :new]
  end
  resources :users, only: [:create, :edit, :update]
end

app/controllers/admin/characters_controller.rb
class Admin::CharactersController < ApplicationController
  before_action :authenticate_staff!

  def destroy
    @character = Character.find_by(slug: params[:id])
    @time_string = Time.now.to_formatted_s(:number)
    if @character.update(archived: true, name: "[Archived: #{@time_string}] #{@character.name}", slug: "archived-#{@time_string}-#{@character.slug}")
      flash[:success] = "Character deleted successfully."
      redirect_to staff_characters_path
    else
      flash.now[:alert] = "There was a problem deleting your character."
      render :show
    end
  end

  def edit
    @character = Character.find_by(slug: params[:id])
  end

  def index
    @characters = Character.where(archived: false)
  end

  def show
    @character = Character.find_by(slug: params[:id])
    @markdown = new_markdown
  end

  def update
    @character = Character.find_by(slug: params[:id])
    if @character.update(staff_character_params)
      flash[:success] = "Character updated successfully."
      redirect_to staff_user_character_path(@character.user, @character)
    else
      flash.now[:alert] = "There was a problem updating your character."
      render :edit
    end
  end

  protected

  def staff_character_params
    params.require(:character).permit(:name, :slug, :race, :user_id, :history)
  end
end

app/controllers/api/v1/characters_controller.rb
class Api::V1::CharactersController < Api::ApiController
  def show
    character = Character.find_by(slug: params[:id])
    render json: character
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  before_action :authenticate_user!

  def create
    @character = Character.new(character_params)
    @character.user = current_user
    if @character.save
      flash[:success] = "Character created successfully."
      redirect_to characters_path
    else
      flash.now[:alert] = "There was a problem creating your character."
      render :new
    end
  end

  def edit
    @character = Character.find_by(slug: params[:id])
    @user = @character.user
    authorize_record_owner(@user)
  end

  def index
    @characters = current_user.characters.where(archived: false)
  end

  def new
    @character = Character.new
  end

  def show
    @character = Character.find_by(slug: params[:id])
    @user = @character.user
    @markdown = new_markdown
    authorize_record_owner(@user)
  end

  def update
    @character = Character.find_by(slug: params[:id])
    @user = @character.user
    authorize_record_owner(@user)
    if @character.update(update_params)
      flash[:success] = "Character updated successfully."
      redirect_to character_path(@character)
    else
      flash.now[:alert] = "There was a problem updating your character."
      render :edit
    end
  end

  protected

  def character_params
    params.require(:character).permit(:name, :race)
  end

  def update_params
    params.require(:character).permit(:history)
  end

end

app/controllers/staff/bio_controller.rb
class Staff::BioController < ApplicationController
  before_action :authenticate_staff!

  def index
    if current_user.staff_profile.present?
      @staff_profile = current_user.staff_profile
    else
      @staff_profile = StaffProfile.new
    end
  end
end

app/controllers/staff/bookings_controller.rb
class Staff::BookingsController < ApplicationController
  before_action :authenticate_staff!

  def index
    @event = Event.find_by(slug: params[:event_id])
  end
end

app/controllers/staff/character_inventories_controller.rb
class Staff::CharacterInventoriesController < ApplicationController
  before_action :authenticate_staff_editor!

  def update
    @character = Character.find_by(slug: params[:id])
    if duplicate_ingredient_ids?(params)
      flash.now[:alert] = "There was a problem updating your component inventory."
      @components = Ingredient.all - @character.ingredients
      @inventories = Inventory.order_by_ingredient_name.where(character: @character)
      render 'staff/inventories/index'
    elsif @character.update(inventory_params)
      flash[:success] = "Component inventory updated successfully."
      redirect_to staff_user_character_path(@character.user, @character)
    else
      flash.now[:alert] = "There was a problem updating your component inventory."
      @components = Ingredient.all - @character.ingredients
      @inventories = Inventory.order_by_ingredient_name.where(character: @character)
      render 'staff/inventories/index'
    end
  end

  protected

  def inventory_params
    params.require(:character).permit(inventories_attributes: [:id, :quantity, :ingredient_id, :unlocked_calcination, :unlocked_concentration, :unlocked_dissolution, :unlocked_extraction, :unlocked_crafting, :unlocked_ritual])
  end

  def duplicate_ingredient_ids?(params)
    ingredient_ids = Array.new
    params[:character][:inventories_attributes].values.each { |inventory| ingredient_ids << inventory[:ingredient_id] unless inventory[:ingredient_id].nil?}
    if ingredient_ids.uniq != ingredient_ids
      true
    else
      false
    end
  end
end

app/controllers/staff/character_recipes_controller.rb
class Staff::CharacterRecipesController < ApplicationController

  def index
    @character = Character.find_by(slug: params[:character_id])
    @recipes = @character.recipes
  end

  def new
    if params.include?(:character_id)
      @character = Character.find_by(slug:params[:character_id])
      @recipes = Recipe.all
    elsif params.include?(:recipe_id)
      @recipe= Recipe.find_by(slug:params[:recipe_id])
      @alchemists = Character.includes(:character_professions).where(archived: false, character_professions: { profession_id: 1 })
    end
    @character_recipe = CharacterRecipe.new
  end

  def create
    if params[:character_id]
      @character = Character.find_by(slug: params[:character_id])
      @recipe = Recipe.find_by_id(params[:character_recipe][:recipe_id])
    else
      @recipe = Recipe.find_by(slug: params[:recipe_id])
      @character = Character.find_by_id(params[:character_recipe][:character_id])
    end
    @character_recipe = CharacterRecipe.new(recipe_id:@recipe.id, character_id:@character.id)
    if @character_recipe.save
      redirect_to staff_user_character_character_recipes_path(@character.user, @character)
    else
      flash[:notice] = "Character Already Knows This Recipe"
      redirect_to staff_user_character_character_recipes_path(@character.user, @character)
    end
  end

end

app/controllers/staff/characters_controller.rb
class Staff::CharactersController < ApplicationController
  before_action :authenticate_staff!
  before_action :authenticate_staff_editor!, except: [:index, :show]

  def destroy
    @character = Character.find_by(slug: params[:id])
    @time_string = Time.now.to_formatted_s(:number)
    if @character.update(archived: true, name: "[Archived: #{@time_string}] #{@character.name}", slug: "archived-#{@time_string}-#{@character.slug}")
      flash[:success] = "Character deleted successfully."
      redirect_to staff_characters_path
    else
      flash.now[:alert] = "There was a problem deleting your character."
      render :show
    end
  end

  def edit
    @character = Character.find_by(slug: params[:id])
    @professions = Profession.order(:name)
  end

  def index
    @characters = Character.where(archived: false)
  end

  def show
    @character = Character.find_by(slug: params[:id])
    @bank_account = BankAccount.where('character_id =?', @character.id)
    @markdown = new_markdown
  end

  def update
    @character = Character.find_by(slug: params[:id])
    if @character.update(staff_character_params)
      flash[:success] = "Character updated successfully."
      redirect_to staff_user_character_path(@character.user, @character)
    else
      flash.now[:alert] = "There was a problem updating your character."
      @professions = Profession.order(:name)
      render :edit
    end
  end

  protected

  def staff_character_params
    params.require(:character).permit(:name, :slug, :race, :user_id, :drake, :history, profession_ids: [], profession_link_ids: [])
  end
end

app/controllers/staff/components_controller.rb
class Staff::ComponentsController < ApplicationController
  before_action :authenticate_staff!
  before_action :authenticate_staff_editor!, except: [:index, :show]
  before_action :fetch_seasons, except: [:destroy]

  def create
    @component = Ingredient.new(ingredient_params)
    if @component.save
      flash[:success] = "Component created successfully."
      redirect_to staff_components_path
    else
      flash.now[:alert] = "There was a problem creating your component."
      @professions = Profession.all
      render :new
    end
  end

  def destroy
    @component = Ingredient.find(params[:id])
    if @component.update(archived: true)
      flash[:success] = "Component deleted successfully."
      redirect_to staff_components_path
    else
      flash.now[:alert] = "There was a problem deleting your component."
      render :edit
    end
  end

  def edit
    @component = Ingredient.find(params[:id])
    @professions = Profession.all
  end

  def index
    @components = Ingredient.where(archived: false).order(:name)
    @professions = Profession.all.map(&:name)
  end

  def new
    @component = Ingredient.new
    @professions = Profession.all
  end

  def show
    @component = Ingredient.find(params[:id])
  end

  def update
    @component = Ingredient.find(params[:id])
    if @component.update(ingredient_params)
      flash[:success] = "Component updated successfully."
      redirect_to staff_component_path(@component)
    else
      flash.now[:alert] = "There was a problem updating your component."
      @professions = Profession.all
      render :edit
    end
  end

  protected

  def fetch_seasons
    @seasons = Season.all
  end

  def ingredient_params
    params.require(:ingredient).permit(:picture, :name, :grade, :category, :rarity, :process_calcination, :process_concentration, :process_dissolution, :process_extraction, :crafting, :ritual_attribute, :ritual_elemental_affinity, :ritual_gender, :ritual_opposite, :staff_notes, profession_ids: [], season_ids: [])
  end
end

app/controllers/staff/entities_controller.rb
class Staff::EntitiesController < ApplicationController
  before_action :authenticate_staff!
  
  def index
    @entities = Entity.all
  end

  def show
    @entity = Entity.find_by(slug:params[:id])
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    if @entity.save!
      redirect_to staff_entity_path(@entity)
    end
  end

  protected
  def entity_params
    params.require(:entity).permit(:name, :description)
  end

end

app/controllers/staff/events_controller.rb
class Staff::EventsController < ApplicationController
  before_action :authenticate_staff_editor!

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Event created successfully."
      redirect_to event_path(@event)
    else
      flash.now[:alert] = "There was a problem creating your event."
      render :new
    end
  end

  def destroy
    @event = Event.find_by(slug: params[:id])
    if @event.update(visible: false)
      flash[:success] = "Event deleted successfully."
      redirect_to events_path
    else
      flash.now[:alert] = "There was a problem deleting your event."
      render :edit
    end
  end

  def edit
    @event = Event.find_by(slug: params[:id])
  end

  def new
    @event = Event.new
  end

  def update
    @event = Event.find_by(slug: params[:id])
    if @event.update(event_params)
      @event.regenerate_slug!
      flash[:success] = "Event updated successfully."
      redirect_to event_path(@event)
    else
      flash.now[:alert] = "There was a problem updating your event."
      render :edit
    end
  end

  protected

  def event_params
    params.require(:event).permit(:address, :directions, :end_date, :latitude, :longitude, :name, :start_date)
  end
end

app/controllers/staff/filters_controller.rb
class Staff::FiltersController < ApplicationController
  before_action :authenticate_staff!

  def show
    @filter_param = params[:id]
    @professions = Profession.all.map(&:name)
    @seasons = Season.all.map(&:name)
    if @filter_param.include?("-")
      @profession = Profession.find_by(name: @filter_param.titleize.gsub(" ", "/"))
    else
      @profession = Profession.find_by(name: @filter_param.titleize)
    end
    if Ingredient.rarities.keys.include?(@filter_param)
      @rarity = @filter_param
    else
      @rarity = nil
    end
    @season = Season.find_by(name: @filter_param.titleize)
    if Ingredient.categories.keys.include?(@filter_param)
      @type = @filter_param
    else
      @type = nil
    end
    if @profession
      @filter_type = :profession
      @components = IngredientProfession.where(profession: @profession).map(&:ingredient)
    elsif @rarity
      @filter_type = :rarity
      @components = Ingredient.where(rarity: @rarity)
    elsif @season
      @filter_type = :season
      @components = IngredientSeason.where(season: @season).map(&:ingredient)
    elsif @type
      @filter_type = :type
      @components = Ingredient.where(category: @type)
    else
      flash[:alert] = "Filter not found."
      redirect_to staff_components_path
    end
  end

end

app/controllers/staff/inventories_controller.rb
class Staff::InventoriesController < ApplicationController
  before_action :authenticate_staff_editor!

  def destroy
    @inventory = Inventory.find(params[:id])
    if @inventory.destroy
      flash[:success] = "#{@inventory.ingredient.name} deleted successfully."
    else
      flash[:alert] = "There was a problem deleting this inventory entry."
    end
    redirect_to staff_user_character_inventories_path(@inventory.character.user, @inventory.character)
  end

  def index
    @character = Character.find_by(slug: params[:character_id])
    @components = Ingredient.by_name - @character.ingredients
    @inventories = Inventory.order_by_ingredient_name.where(character: @character)
  end
end

app/controllers/staff/pictures_controller.rb
class Staff::PicturesController < ApplicationController
  before_action :authenticate_staff!

  def index
    @components = Ingredient.where(archived: false).where.not(picture: nil).order(:name)
  end
end

app/controllers/staff/professions_controller.rb
class Staff::ProfessionsController < ApplicationController
  before_action :authenticate_staff!

  def index
    @professions = Profession.order(:name)
  end

  def show
    @profession = Profession.find(params[:id])
  end
end

app/controllers/staff/profiles_controller.rb
class Staff::ProfilesController < ApplicationController
  before_action :authenticate_staff!

  def index
    if current_user.staff_profile.present?
      @staff_profile = current_user.staff_profile
    else
      @staff_profile = StaffProfile.new
    end
  end
end

app/controllers/staff/receipts_controller.rb
class Staff::ReceiptsController < ApplicationController
  before_action :authenticate_staff!

  def show
    @receipt = Receipt.find(params[:id])
  end
end

app/views/staff/characters/edit.html.haml
.row
  .small-12.columns
    %nav{"aria-label": "You are here:", role: "navigation"}
      %ul.breadcrumbs
        %li
          =link_to "Users", staff_users_path
        %li
          =link_to @character.user.handle, staff_user_path(@character.user)
        %li
          =link_to "Characters", staff_characters_path
        %li
          =link_to @character.name, staff_user_character_path(@character.user, @character)
        %li
          %span.show-for-sr Current:
          Edit
    %h1.text-center
      Edit
      =@character.name
    =form_for [:staff, @character] do |f|
      .form-inputs
        .row
          .small-12.medium-6.columns
            %fieldset
              =render partial: "text_field_with_errors", locals: {attribute: :name, form: f, model: @character}
          .small-12.medium-6.columns
            %fieldset
              =render partial: "text_field_with_errors", locals: {attribute: :slug, form: f, model: @character}
        .row
          .small-12.medium-6.columns
            %fieldset
              =f.label :race, "Race"
              =f.select :race, options_for_select(Character.enum_collection(:races), @character.race)
          .small-12.medium-6.columns
            %fieldset
              =f.label :user_id, "User"
              =f.select :user_id, options_from_collection_for_select(User.by_name, 'id', 'label', @character.user.id)
        %fieldset.fieldset
          %legend Professions
          =f.collection_check_boxes :profession_ids, @professions, :id, :name
        =f.label :drake
        =f.number_field :drake, min: 0
        =f.label :history, "Character History"
        =f.text_area :history
      .form-actions
        =f.submit "Save", class: "button"

app/views/staff/characters/index.html.haml
.row
  .small-12.columns
    %h1.text-center Characters
    %table.hover.stack.datatables{ data: { page: { length: "100" } } }
      %thead
        %tr
          %th Name
          %th Race
          %th User
          %th Wealth
      %tbody
        -@characters.each do |character|
          %tr
            %td= link_to character.name, staff_user_character_path(character.user, character)
            %td= character.race.titleize
            %td= link_to character.user.label, staff_user_path(character.user)
            %td{ data: { order: character.drake } }
              -unless character.drake.nil?
                =number_with_delimiter(character.drake)
                Drake

app/views/staff/characters/show.html.haml
.row
  .small-12.columns
    %nav{"aria-label": "You are here:", role: "navigation"}
      %ul.breadcrumbs
        %li
          =link_to "Users", staff_users_path
        %li
          =link_to @character.user.handle, staff_user_path(@character.user)
        %li
          =link_to "Characters", staff_characters_path
        %li
          %span.show-for-sr Current:
          =@character.name
    %h1.text-center
      =@character.name
      -if current_user.editor?
        =link_to edit_staff_user_character_path(@character.user, @character) do
          %i.fa.fa-pencil-square-o{"aria-hidden": "true"}
        =link_to staff_character_path(@character), method: :delete, data: { confirm: "Delete character '#{@character.name}': are you sure?" } do
          %i.fa.fa-trash{"aria-hidden": "true"}
      %a{"data-open": "historyModal"}
        %i.fa.fa-book{"aria-hidden": "true"}
      -if @character.alchemist?
        =link_to staff_user_character_character_recipes_path(@character.user, @character) do
          %i.fa.fa-flask{"aria-hidden": "true"}
      -unless @character.bank_account.nil?
        =link_to character_bank_account_path(@character, @character.bank_account) do
          %i.fa.fa-diamond{"aria-hidden": "true"}
    %h3.text-center= @character.race.titleize
    -unless @character.drake.nil?
      %p.text-center
        =number_with_delimiter(@character.drake)
        Drake
    -if @character.inventories.empty?
      -if current_user.editor?
        %p.text-center
          =link_to staff_user_character_inventories_path(@character.user, @character), class: "button" do
            %i.fa.fa-list-ol
            Edit Components Inventory
    -else
      .callout
        %h2.text-center
          Components Inventory
          -if current_user.editor?
            =link_to staff_user_character_inventories_path(@character.user, @character) do
              %i.fa.fa-list-ol{"aria-hidden": "true"}
        %table.hover.datatables{ data: { page: { length: "25" }, order: "[[1,\"asc\"]]" } }
          %thead
            %tr
              %th.text-right Quantity
              %th Component
              %th.text-center Extraction
              %th.text-center Calcination
              %th.text-center Dissolution
              %th.text-center Concentration
              %th.text-center Crafting
              %th.text-center Ritual
          %tbody
            -@character.inventories.each do |inventory|
              %tr
                %td.text-right= inventory.quantity
                %td
                  =inventory.ingredient.name
                  -if inventory.ingredient.picture.present?
                    %a.float-right{ data: { open: inventory.ingredient.name.parameterize } }
                      %i.fa.fa-eye
                %td.text-center
                  -if inventory.unlocked_extraction?
                    =inventory.ingredient.process_extraction
                  -else
                    %i.fa.fa-lock
                %td.text-center
                  -if inventory.unlocked_calcination?
                    =inventory.ingredient.process_calcination
                  -else
                    %i.fa.fa-lock
                %td.text-center
                  -if inventory.unlocked_dissolution?
                    =inventory.ingredient.process_dissolution
                  -else
                    %i.fa.fa-lock
                %td.text-center
                  -if inventory.unlocked_concentration?
                    =inventory.ingredient.process_concentration
                  -else
                    %i.fa.fa-lock
                %td.text-center
                  -if inventory.unlocked_crafting?
                    =inventory.ingredient.crafting
                  -else
                    %i.fa.fa-lock
                %td.text-center
                  -if inventory.unlocked_ritual?
                    =inventory.ingredient.ritual_properties.to_sentence
                  -else
                    %i.fa.fa-lock
    -unless @character.professions.empty?
      .callout
        %h2.text-center Professions
        %ul.tabs#profession-tabs{ data: { tabs: "" } }
          -@character.professions.order(:name).each do |profession|
            %li.tabs-title
              %a{ href: "##{profession.name.parameterize}" }= profession.name
        .tab-content{ data: { tabs: { content: "profession-tabs" } } }
          -if current_user.editor?
            =form_for [:staff, @character] do |f|
              -@character.professions.order(:name).each do |profession|
                .tabs-panel{id: profession.name.parameterize}
                  -if profession.profession_links.empty?
                    %p (No links currently available.)
                  -else
                    %ol
                      =f.collection_check_boxes :profession_link_ids, profession.profession_links.order(:name), :id, :name do |b|
                        %li
                          =b.label { b.text + " " + b.check_box }
                    =f.submit "Save", class: "button"
          -else
            -@character.professions.order(:name).each do |profession|
              .tabs-panel{id: profession.name.parameterize}
                -if profession.profession_links.empty?
                  %p (No links currently available.)
                -else
                  %ol
                    -profession.profession_links.order(:name).each do |link|
                      %li
                        -if @character.profession_links.include?(link)
                          %i.fa.fa-eye
                        -else
                          %i.fa.fa-lock
                        =link_to link.name, link.url, target: "_blank"
.reveal#historyModal{"data-reveal": ""}
  %h2.margin-bottom-none.text-center Character History
  %hr/
  -if @character.history.blank?
    %p
      %em (blank)
  -else
    =raw @markdown.render(@character.history)
  %button.close-button{"data-close": "", "aria-label": "Close modal", "type": "button"}
    %span{"aria-hidden": "true"}
      &times;
-@character.inventories.each do |inventory|
  -if inventory.ingredient.picture.present?
    .reveal{ id: "#{inventory.ingredient.name.parameterize}", data: { reveal: "" } }
      %span.label= inventory.ingredient.name
      =image_tag(inventory.ingredient.picture.url, alt: "Picture of #{inventory.ingredient.name}")
      %button.close-button{ data: { close: "" }, aria: { label:  "Close modal"}, type: "button" }
        %span{ aria: { hidden: "true" } }
          &times;