config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "staff-menu", to: "pages#staff_menu", as: :staff_menu
  get "sign-in", to: "sessions#new", as: :sign_in
  post "sign-in", to: "sessions#create"
  delete "sign-out", to: "sessions#destroy"
  get "sign-up", to: "users#new", as: :sign_up

  namespace :staff do
    namespace :review do
      resources :staff_profiles, only: [:update]
    end
    resources :characters, only: [:destroy, :index, :update]
    resources :character_inventories, only: [:update]
    resources :components, except: [:create, :destroy, :update] do
      collection do
        resources :filters, only: [:show]
        resources :pictures, only: [:index]
      end
    end
    resources :events, only: [:create, :destroy, :edit, :new, :update] do
      resources :bookings, only: [:index]
      resources :self_reports, only: [:index]
    end
    resources :ingredients, controller: :components, only: [:create, :destroy, :update]
    resources :inventories, only: [:destroy]
    resources :professions, only: [:index, :show]
    resources :profession_links, only: [:create, :new, :update]
    resources :profiles, only: [:index]
    resources :recipes do
      resources :character_recipes, only: [:new, :create]
    end
    resources :receipts, only: [:show]
    resources :review_profiles, only: [:index]
    resources :staff_profiles, only: [:create, :update]
    resources :users, only: [:index, :show] do
      resources :characters, only: [:edit, :show] do
        resources :character_recipes, only: [:index, :new, :create, :show]
        resources :inventories, only: [:index]
      end
    end
    resources :recipes
    resources :user_staff_statuses, only: [:update]
    resources :user_editor_statuses, only: [:update]
  end

  resources :account_confirmations, only: [:edit]
  resources :bank_accounts
  resources :bookings, only: [:new, :update]
  resources :cash_bookings, only: [:new, :create]
  resources :characters, only: [:create, :edit, :index, :new, :show, :update] do
    resources :character_recipes, only:[:index, :show]
    resources :ingredient_transfers, only:[:new, :create]
    resources :bank_accounts, only: [:show, :edit, :new] do
      resources :bank_transactions
    end
  end
  resources :events, only: [:index, :show]
  resources :password_resets, only: [:create, :edit, :new, :update]
  resources :receipts, only: [:create]
  resources :recipes, only:[:show]
  resources :staff, only: [:index] do
    resources :messages, only: [:create, :new]
  end
  resources :users, only: [:create, :edit, :update]
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :character, optional: true
  belongs_to :entity, optional:true
  has_many :bank_transactions

  def self.has_account?(character_id)
    account = BankAccount.where('character_id = ?', character_id)
    if account.length > 0
      return true
    end
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :authenticate_banker_or_staff!, only: [:create, :index]

  def index
    @accounts = BankAccount.all
    @characters_without_accounts = Character.includes(:bank_account).where(archived: false, bank_accounts: { id: nil }).alpha_by_name
    @account = BankAccount.new
  end

  def show
    @character = Character.find_by(slug: params[:character_id])
    if !current_user.banker && !current_user.staff
      authorize_user(@character.user)
    end
    @account = @character.bank_account
    @transactions = @account.bank_transactions
    @user = current_user
  end

  def create
    @account = BankAccount.new(account_params)
    if @account.save
      BankTransaction.create(
        bank_account_id:@account.id,
        transaction_type: "Initial Deposit",
        transaction_amount: @account.balance
      )
      redirect_to character_bank_account_path(@account.character,@account)
    else
      flash[:notice]="Account add failed"
    end
  end

  def authorize_user(user)
    unless user == current_user
      flash[:alert] = "You are not authorized for this record."
      redirect_to root_path
    end
  end

  protected

  def account_params
    params.require(:bank_account).permit(:character_id, :balance)
  end
end

app/views/bank_accounts/index.html.erb
<div class="row">
  <h1 class="bankHeader">Bank of Derrickham</h1>
  <div class="row">
    <table role="grid" class="row">
      <thead class="row">
        <th>Character</th>
        <th>Balance</th>
      </thead>
      <tbody>
        <% @accounts.each do |account| %>
        <tr>
          <td><%=link_to "#{account.character.name}", character_bank_account_path(account.character, account)%></td>
          <td><%=account.balance%> Drake</td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <h1>Create a new account</h1>
    <%= form_for(@account) do |f| %>

    <%= f.label  :character_id, "Character" %>
    <%= f.collection_select(:character_id,@characters_without_accounts, :id,:name,{include_blank: true}, class: "characterSelect")%>

    <%= f.label :balance, "Starting Balance" %>
    <%= f.text_field :balance, class:"startingBalance" %>

    <%= f.submit "Create Bank Account", class:"button" %>
    <% end %>

  </div>
</div>

app/views/bank_accounts/show.html.erb
<div class="row">
<h1 class="bankHeader"> <%= link_to "Bank of Derrickham", bank_accounts_path %> </h1>
<h3> <%= @character.name %>'s Bank Account - Balance: <%= @account.balance  %> Drake</h3>
<div> </div>
<% if @user.staff? || @user.banker? %>
<div class="row">
<%= link_to "New Transaction", new_character_bank_account_bank_transaction_path(@character,@account),class:"button" %>
</div>
<% end %>

<div class="row">
  <h1>Transaction History</h1>
  <table role="grid" class="row">
    <thead class="row">
      <th>date</th>
      <th>time</th>
      <th>type</th>
      <th>amount</th>
    </thead>
    <tbody>
<% @transactions.each do |tran| %>
<tr>
  <td><%= tran.created_at.strftime("%D") %></td>
  <td><%= tran.created_at.strftime("%R") %></td>
  <td><%= tran.transaction_type %></td>
  <td><%= tran.transaction_amount %> Drake</td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>