config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "staff-menu", to: "pages#staff_menu", as: :staff_menu
  get "sign-in", to: "sessions#new", as: :sign_in
  post "sign-in", to: "sessions#create"
  delete "sign-out", to: "sessions#destroy"
  get "sign-up", to: "users#new", as: :sign_up

  namespace :staff do
    namespace :review do
      resources :staff_profiles, only: [:update]
    end
    resources :characters, only: [:destroy, :index, :update]
    resources :character_inventories, only: [:update]
    resources :components, except: [:create, :destroy, :update] do
      collection do
        resources :filters, only: [:show]
        resources :pictures, only: [:index]
      end
    end
    resources :events, only: [:create, :destroy, :edit, :new, :update] do
      resources :bookings, only: [:index]
      resources :self_reports, only: [:index]
    end
    resources :ingredients, controller: :components, only: [:create, :destroy, :update]
    resources :inventories, only: [:destroy]
    resources :professions, only: [:index, :show]
    resources :profession_links, only: [:create, :new, :update]
    resources :profiles, only: [:index]
    resources :recipes do
      resources :character_recipes, only: [:new, :create]
    end
    resources :receipts, only: [:show]
    resources :review_profiles, only: [:index]
    resources :staff_profiles, only: [:create, :update]
    resources :users, only: [:index, :show] do
      resources :characters, only: [:edit, :show] do
        resources :character_recipes, only: [:index, :new, :create, :show]
        resources :inventories, only: [:index]
      end
    end
    resources :recipes
    resources :user_staff_statuses, only: [:update]
    resources :user_editor_statuses, only: [:update]
  end

  resources :account_confirmations, only: [:edit]
  resources :bank_accounts
  resources :bookings, only: [:new, :update]
  resources :cash_bookings, only: [:new, :create]
  resources :characters, only: [:create, :edit, :index, :new, :show, :update] do
    resources :character_recipes, only:[:index, :show]
    resources :ingredient_transfers, only:[:new, :create]
    resources :bank_accounts, only: [:show, :edit, :new] do
      resources :bank_transactions
    end
  end
  resources :events, only: [:index, :show]
  resources :password_resets, only: [:create, :edit, :new, :update]
  resources :receipts, only: [:create]
  resources :recipes, only:[:show]
  resources :staff, only: [:index] do
    resources :messages, only: [:create, :new]
  end
  resources :users, only: [:create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEXP = /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  HANDLE_REGEXP = /\A[A-Za-z0-9]+(?:[_-][A-Za-z0-9]+)*\z/

  attr_accessor :confirmation_token, :password_reset_token, :remember_token

  before_create :generate_confirmation_digest
  before_save :downcase_email

  has_many :bookings
  has_many :events, through: :bookings
  has_many :characters
  has_many :transactions
  has_one :staff_profile

  has_secure_password

  validates_format_of :email, with: EMAIL_REGEXP
  validates_format_of :handle, with: HANDLE_REGEXP, message: "may only contain letters, numbers, dashes, and underscores (no spaces or other special characters), and must begin with a letter or number"
  validates_inclusion_of :editor, in: [true, false]
  validates_inclusion_of :staff, in: [true, false]
  validates_length_of :handle, in: 3..30
  validates_presence_of :email, :first_name, :handle, :last_name
  validates_uniqueness_of :email, :handle

  scope :by_name, -> { order(:first_name) }
  scope :confirmed, -> { where.not(confirmed_at: nil) }

  def assign_attributes_from_receipt(hash)
    assign_attributes(
      phone: hash[:phone],
      street_address: hash[:street],
      city: hash[:city],
      state: hash[:state],
      zip: hash[:zip],
      self_report: hash[:report]
    )
  end

  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def confirm!
    touch(:confirmed_at) if confirmed_at.nil?
  end

  def confirmed?
    !confirmed_at.nil?
  end

  def downcase_email
    self.email.downcase!
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def generate_remember_digest
    self.remember_token = User.new_token
    update_attributes(remember_digest: User.digest(remember_token))
  end

  def generate_reset_digest
    self.password_reset_token = User.new_token
    update_attributes(password_reset_digest: User.digest(password_reset_token), password_reset_sent_at: Time.current)
  end

  def label
    if staff?
      "#{first_name} #{last_name} (#{handle}*)"
    else
      "#{first_name} #{last_name} (#{handle})"
    end
  end

  def password_reset_expired?
    (password_reset_sent_at + 2.hours).past?
  end

  def send_confirmation_email
    UserMailer.account_confirmation(self.id, self.confirmation_token).deliver_now
  end

  def send_password_reset_email
    UserMailer.password_reset(self.id, self.password_reset_token).deliver_now
  end

  def terminate_remember_digest
    update_attributes(remember_digest: nil)
  end

  def to_param
    handle
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  protected

  def generate_confirmation_digest
    self.confirmation_token = User.new_token
    self.confirmation_digest = User.digest(confirmation_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_staff!

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(handle: params[:id])
  end
end

app/controllers/staff/users_controller.rb
class Staff::UsersController < ApplicationController
  before_action :authenticate_staff!

  def index
    @users = User.confirmed
  end

  def show
    @user = User.find_by(handle: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update]
  before_action :prevent_duplicate_sign_in, only: [:create, :new]

  def create
    @user = User.new(user_params)
    if verify_recaptcha(model: @user) && @user.save
      @user.send_confirmation_email
      flash[:success] = "Registration successful. Please confirm your email to activate your account."
      redirect_to root_path
    else
      flash.now[:alert] = "There was a problem with your registration."
      render :new
    end
  end

  def edit
    @user = User.find_by(handle: params[:id])
    authorize_user(@user)
  end

  def new
    @user = User.new
  end

  def update
    @user = User.find_by(handle: params[:id])
    authorize_user(@user)
    if @user.authenticate(params[:user][:password])
      @user.assign_attributes(update_params)
      if @user.changed.include?("email") && @user.valid?
        @user.confirmed_at = nil
        @user.send(:generate_confirmation_digest)
        @reconfirm = true
        sign_out
      end
      if @user.save
        if @reconfirm
          @user.send_confirmation_email
          flash[:success] = "Update successful. Please confirm your email to re-activate your account."
        else
          flash[:success] = "Update successful."
        end
        redirect_to root_path
      else
        flash.now[:alert] = "There was a problem with your update."
        render :edit
      end
    else
      flash.now[:alert] = "There was a problem with your update."
      render :edit
    end
  end

  protected

  def authorize_user(user)
    unless user == current_user
      flash[:alert] = "You are not authorized for this record."
      redirect_to root_path
    end
  end

  def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new sign_up_params
      respond_with_navigational(resource) { render :new }
    end
  end

  def update_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end

  def user_params
    params.require(:user).permit(:handle, :email, :first_name, :last_name, :password, :password_confirmation)
  end

end

app/views/admin/users/index.html.haml
.row
  .small-12.columns
    %h1.text-center.top-padded Users
    %table.hover.stack.datatables
      %thead
        %tr
          %th Username
          %th Email
          %th First Name
          %th Last Name
          %th Admin
      %tbody
        -@users.each do |user|
          %tr
            %td= link_to user.handle, staff_user_path(user)
            %td= link_to user.email, "mailto:#{user.email}"
            %td= user.first_name
            %td= user.last_name
            %td
              -if user.staff?
                %i.fa.fa-star
              =user.staff?

app/views/admin/users/show.html.haml
.row
  .small-12.columns
    %nav.top-padded{"aria-label": "You are here:", role: "navigation"}
      %ul.breadcrumbs
        %li
          =link_to "Users", staff_users_path
        %li
          %span.show-for-sr Current:
          =@user.handle
    %h1.text-center
      -if @user.staff?
        %i.fa.fa-star
      =@user.handle
      =form_for @user, url: staff_user_staff_status_path(@user) do |f|
        .form-actions
          -if @user.staff?
            =f.submit "Revoke Admin Privileges", class: "button", data: { confirm: "Revoke staffistrative privileges from user '#{@user.handle}': are you sure?" }
          -else
            =f.submit "Grant Admin Privileges", class: "button", data: { confirm: "Grant staffistrative privileges to user '#{@user.handle}': are you sure?" }
    %p
      %strong Name:
      =@user.full_name
    %p
      %strong Email:
      =link_to @user.email, "mailto:#{@user.email}"
    %p
      %strong Member For:
      =distance_of_time_in_words_to_now(@user.created_at)
    %p
      %strong Last Signed In:
      -if @user.last_signed_in_at.nil?
        %em Never
      -else
        =distance_of_time_in_words_to_now(@user.last_signed_in_at)
        ago
    -unless @user.characters.empty?
      %h3.text-center Characters
      %table.hover.stack.datatables
        %thead
          %tr
            %th Name
            %th Race
        %tbody
          -@user.characters.each do |character|
            %tr
              %td= link_to character.name, staff_user_character_path(character.user, character)
              %td= character.race.titleize